### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/knowledge#105]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] document_ocr - By @cmsalmeida - #140 
- [x] document_url - By @difusionvisual - #111 
- [x] knowledge - By @LeartS - #118 
- [x] document_page by @max3903 in #120 
- [x] document_page_approval  by @max3903 in #122 
- [x] attachment_preview - By @tarteo - #224 
- [x] attachments_to_filesystem
- [x] document_choose_directory
- [x] document_multiple_records
- [x] document_no_unique_filenames
- [x] document_page_multi_company
- [x] document_reindex

**Comment by LeartS** [comment]
Porting of knowledge here: https://github.com/OCA/knowledge/pull/118

**Comment by max3903** [comment]
Anyone to review #122? Thank you.

**Comment by MakMas** [comment]
Hello,

I'm new here, can some one help me with this module?
I'm migrate two weeks ago on the Odoo v.10 and I need module Knowledge on my system.
I'm downloaded module *Knowledge* from this link https://github.com/OCA/knowledge/tree/10.0/document_url and copy to my folder with another modules. When I try to install this module i have many different mistake.....maybe I do something wrong?

**Comment by max3903** [comment]
Hello @MakMas 

Please create a new issue. This one is used for the migration status.

**Comment by MakMas** [comment]
Ok, thank you

**Comment by tarteo** [comment]
attachment_preview is done by https://github.com/OCA/knowledge/pull/224
