### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/knowledge#147]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] attachment_attach_non_editable
- [x] attachment_preview - ~~By @fayezqandeel - #150~~ By @tarteo - #175 
- [ ] attachments_to_filesystem
- [ ] document_choose_directory
- [ ] document_multiple_records
- [ ] document_no_unique_filenames
- [x] document_page - ~~By @jalzaga - #157 - By @GavyMG - #173~~ #174 
- [x] document_page_approval - By @GavyMG - #171 
- [ ] document_page_multi_company
- [ ] document_reindex
- [x] document_url - By @ernestotejeda - #164 
- [x] knowledge - ~~By @fayezqandeel - #149~~ By @cubells - #170

**Comment by fayezqandeel** [comment]
@pedrobaeza I 'm going to start migrating knowledge module

**Comment by pedrobaeza** [comment]
@fayezqandeel Noted in the main comment

**Comment by fayezqandeel** [comment]
@pedrobaeza I will work on attachment_preview

**Comment by ferdiga** [comment]
please can you describe what are the tasks for the migration of the modules.
I am familiar with 6.1 and 8.0 (old stile)

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0.

**Comment by jalzaga** [comment]
Migration to version 11.0.  @pedrobaeza  I'm goin to migrate document_page module. It depends on knowledge module, that is already started migration by @fayezqandeel.

**Comment by SalahAdDin** [comment]
What's about this module? We need it here.

**Comment by GavyMG** [comment]
@pedrobaeza 

I'm migrating document_page_approval. 
@jalzaga could you update and continue the document_page migration?

**Comment by SalahAdDin** [comment]
@cubells There is a missing option menu in `Knowledge` section:
![noesta](https://user-images.githubusercontent.com/5034215/41641970-a2c19164-746f-11e8-806c-085c3c27df04.png)

We can go to options in settings:
![aquiesta](https://user-images.githubusercontent.com/5034215/41641983-ab0f3b82-746f-11e8-9004-59d57c3b4b0b.png)

**Comment by cubells** [comment]
@SalahAdDin you are right.

Can you review this: https://github.com/OCA/knowledge/pull/172

**Comment by tarteo** [comment]
https://github.com/OCA/knowledge/pull/175 supersedes https://github.com/OCA/knowledge/pull/150 for attachment_preview.

**Comment by ivantodorovich** [comment]
I'd like to migrate `document_page_multi_company`, but instead of migrating the module I'd like to introduce this feature in `document_page`. Would that be ok?

---

btw, `document_page_approval` migration PR https://github.com/OCA/knowledge/pull/171 is already merged. 

Although, both `document_page` and `document_page_approval` are behind `10.0` until these are merged:
- https://github.com/OCA/knowledge/pull/185 
- https://github.com/OCA/knowledge/pull/186

**Comment by pedrobaeza** [comment]
> I'd like to migrate document_page_multi_company, but instead of migrating the module I'd like to introduce this feature in document_page. Would that be ok?

I agree
