### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/knowledge#366]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] attachment_preview - By @houzefa-abba - #434
- [x] attachment_zipped_download - By @FernandoRomera - #391
- [x] document_page - By @etobella - #382
- [x] document_page_access_group - By @Tisho99 - #470
- [x] document_page_approval - By @FernandoRomera - #388
- [x] document_page_group - By @FernandoRomera - #383
- [x] document_page_partner - By @ntsirintanis - #465
- [x] document_page_project - By @ntsirintanis - #464
- [x] document_page_reference - By @kaynnan - #422
- [x] document_page_tag - By @FernandoRomera - #384
- [x] document_url - By @FernandoRomera - #385
- [x] knowledge > document_knowledge - By @marielejeune - #368

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by HarhuTechnologies** [comment]
Hi @sbidoul : I want raise a PR against these modules. I have already migrated. Can you please help me how can I create a PR against this issue? @pedrobaeza

**Comment by pedrobaeza** [comment]
Do the pull request, and someone will link through the bot command the PR in this issue. Please follow the migration guide for proper migration mechanism.

**Comment by pedrobaeza** [comment]
Another thing: `knowledge` must be renamed to `knowledge_oca` or similar for not collapsing with Odoo new enterprise module.

**Comment by HarhuTechnologies** [comment]
alright @pedrobaeza : Thanks for letting me know. I will create PR.

**Comment by pegonzalezspesol** [comment]
working on document_page

**Comment by vancouver29** [comment]
> # Todo
> https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0
> 
> # Modules to migrate
> * [ ]  attachment_zipped_download - By @FernandoRomera - [[16.0][MIG] attachment_zipped_download: Migration to 16.0 #391](https://github.com/OCA/knowledge/pull/391)
> * [x]  document_page - By @etobella - [[16.0][MIG] document_page: Migration to 16.0 #382](https://github.com/OCA/knowledge/pull/382)
> * [ ]  document_page_approval - By @FernandoRomera - [[16.0][MIG] document_page_approval: Migration to 16.0 #388](https://github.com/OCA/knowledge/pull/388)
> * [ ]  document_page_group - By @FernandoRomera - [[16.0][MIG] document page group: Migration to 16.0 #383](https://github.com/OCA/knowledge/pull/383)
> * [ ]  document_page_reference
> * [ ]  document_page_tag - By @FernandoRomera - [[16.0][MIG] document page tag: Migration to 16.0 #384](https://github.com/OCA/knowledge/pull/384)
> * [ ]  document_url - By @FernandoRomera - [[16.0][MIG] document url: Migration to 16.0 #385](https://github.com/OCA/knowledge/pull/385)
> * [x]  knowledge > document_knowledge - By @marielejeune - [[16.0] [MIG] knowledge and rename it as document_knowledge #368](https://github.com/OCA/knowledge/pull/368)
> 
> Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

@sbidoul  How about the module `attachment_preview` in v16? the standard attachment preview feature in Odoo core is just for pdf files. For other file types like `odt, odp, ods, fodt, ott, fodp, top, fods, ots` is this feature not available

**Comment by etobella** [comment]
The list was generated with the modules present on the previous version. Other modules might be added

**Comment by gurneyalex** [comment]
@vancouver29 and the preview of Odoo is only for 1 of the PDFs, not all.

**Comment by houzefa-abba** [comment]
Hi I've been working on `attachment_preview` in <https://github.com/OCA/knowledge/pull/434>, not ready yet but getting close!
Update: Ready! :)

**Comment by bnisevic** [comment]
If [houzefa-abba](https://github.com/houzefa-abba) already fixed the attachment_preview, and that was the only missing part. Why we do not have v16 release yet?
