### ISSUE TITLE
Migration to version 8

### ISSUE THREAD

**Issue by max3903** [OCA/knowledge#47]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8
# Modules to migrate
- [x] attachment_preview by @hbrunn in #33 
- [x] attachments_to_filesystem by @hbrunn in #35 
- [x] document_choose_directory by @hbrunn in #36 
- [ ] document_multiple_records
- [x] document_page_approval     by @llacroix in #30 
- [ ] document_page_multi_company 
- [x] document_url by @pedrobaeza in #22 
# Modules from Odoo SA
- [x] document_page by @gborelli  in #24
