### ISSUE TITLE
Migration to version 9

### ISSUE THREAD

**Issue by max3903** [OCA/knowledge#71]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] knowledge by @naousse in #75 
- [ ] document_page by @naousse in #76 
- [ ] document_page_approval by @naousse in #77 
- [ ] attachment_preview
- [ ] attachments_to_filesystem
- [ ] document_choose_directory
- [ ] document_no_unique_filenames
- [ ] document_reindex
- [ ] document_url
